language: php
os: linux
dist: bionic

addons:
  apt:
    packages:
    - mysql-server-5.7
    - mysql-client-core-5.7
    - mysql-client-5.7

git:
  depth: 5

php:
  - 7.2
  - 7.3
  - 7.4

cache:
  - directories:
      # Cache vendor folder will speed up environment setup
      - vendor

services:
  - mysql

env:
  # Here we list the profiles that we want to test, each one will be tested, per version of PHP, in parallel
  - PROFILE=testing

before_install:
  # Remove xdebug to increase speed
  - phpenv config-rm xdebug.ini
  # Set up database
  - tests/database_setup.sh

install:
  # Create setup.php
  - ln -s .travis.setup.php setup.php
  - composer update --prefer-dist
  # Install the testing profile
  - tests/profile_setup.sh "$PROFILE"

before_script:
  # Go into the tests directory to run the tests
  - cd tests/

branches:
  only:
    - develop
    - master
    - master-fix
